name: Weekly Branding Update

on:
  schedule:
    - cron: "0 0 * * 0" # Every Sunday at 00:00 UTC

jobs:
  update-branding:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Update Traffic Badge
        uses: yi-Xu-0100/traffic-to-badge@v1.4.0
        with:
          repository: ${{ github.repository }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate Repo List
        uses: yi-Xu-0100/repo-list-generator@v1.1.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
